# Generated by Django 5.2.6 on 2025-10-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_profile',
            name='staff_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
