# Generated by Django 5.2.7 on 2025-10-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_staff_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.staff_profile'),
        ),
    ]
