# Generated by Django 5.2.6 on 2025-10-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pet_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentService',
        ),
    ]
